# Generated by Django 4.2.6 on 2023-10-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmetrics', '0002_remove_supplier_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
