# Generated by Django 4.2.6 on 2023-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmetrics', '0003_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
