# Generated by Django 4.2.6 on 2023-10-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesmetrics', '0005_use_one_to_one_relationship_on_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesmetrics.paymentmethod'),
        ),
    ]
