# Generated by Django 4.2.6 on 2023-10-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesmetrics', '0008_create_supervisorbranchhistory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='supervisorbranchhistory',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesmetrics.supervisor'),
        ),
    ]
